/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-05-02 09:40:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class start_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/jsp/left.jsp", Long.valueOf(1525248750999L));
    _jspx_dependants.put("/jsp/Dibutu.jsp", Long.valueOf(1525248617581L));
    _jspx_dependants.put("/jsp/top.jsp", Long.valueOf(1525248916069L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
String rgPath=request.getContextPath();
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>在线评测系统</title>\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t    <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/yhz.css\" rel=\"stylesheet\">\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/bootstrap.min.js\"></script>   \r\n");
      out.write("\t    <script src=\"");
      out.print(request.getContextPath());
      out.write("/Content/jsml5shiv.min.js\"></script>\r\n");
      out.write("\t    <script src=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/respond.js\"></script>\r\n");
      out.write("\t    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\">\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"navbar navbar-inverse navbar-fixed-top\" style=\"z-index=1;\">\r\n");
      out.write("       <iframe  src='about:blank' frameBorder='0' marginHeight='0' marginWidth='0' style='position: absolute; visibility: inherit; top: 0px; left: 0px; width: 100%; height: 100%; z-index: -1; filter: alpha(opacity = 0);'></iframe>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"navbar-brand\" style=\"display:inline;\">在线评测系统</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navbar-collapse collapse\">\r\n");
      out.write("\r\n");
      out.write("                <form action=\"\" id=\"logoutForm\" method=\"post\">\r\n");
      out.write("                    <input name=\"__RequestVerificationToken\" type=\"hidden\" value=\"lxn8TVWdVXH2D--PKXECf803v0PAOoe6ypTiFW-JWv4ntU879B2MSPLOLTcL9G66fTk4tIKJ5h7Q0P2nGKnoswT59PwXOH3jylZMhxeEPWzUz_KBjFuS_fW0e6536Kq3VpOZxNbAtVbjTDeYX3nY4w2\">        \r\n");
      out.write("                    <div class=\"navbar-right loginpartial\">\r\n");
      out.write("                        <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usermap.UserName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>&nbsp;|&nbsp;\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/Exit.do\">注销</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>     \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("    <br/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <div class=\"container content-body\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xs-3\">\r\n");
      out.write("              ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\" >\r\n");
      out.write("    <div class=\"sidebar-title\">\r\n");
      out.write("       \t 功能菜单\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /jsp/left.jsp(8,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/left.jsp(8,4) '${muneList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${muneList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /jsp/left.jsp(8,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("ml");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("    <div class=\"sub-title\">\r\n");
              out.write("    <a href=\"");
              out.print(request.getContextPath());
              out.write('/');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.treeUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("\" target=\"_parent\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.treeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</a>\r\n");
              out.write("    </div>\r\n");
              out.write("    ");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("     \r\n");
      out.write("                           \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xs-9\">             \r\n");
      out.write("                   <div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("<div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("  <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-heading\">\r\n");
      out.write("      <h4 class=\"panel-title\">\r\n");
      out.write("        <a data-toggle=\"collapse\" data-parent=\"#accordion\" \r\n");
      out.write("          href=\"#collapseOne\">\r\n");
      out.write("          点击我进行展开，再次点击我进行折叠。第 1 部分\r\n");
      out.write("        </a>\r\n");
      out.write("      </h4>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("      <div class=\"panel-body\">\r\n");
      out.write("        Nihil anim keffiyeh helvetica, craft beer labore wes anderson \r\n");
      out.write("        cred nesciunt sapiente ea proident. Ad vegan excepteur butcher \r\n");
      out.write("        vice lomo.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-heading\">\r\n");
      out.write("      <h4 class=\"panel-title\">\r\n");
      out.write("        <a data-toggle=\"collapse\" data-parent=\"#accordion\" \r\n");
      out.write("          href=\"#collapseTwo\">\r\n");
      out.write("          点击我进行展开，再次点击我进行折叠。第 2 部分\r\n");
      out.write("        </a>\r\n");
      out.write("      </h4>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseTwo\" class=\"panel-collapse collapse\">\r\n");
      out.write("      <div class=\"panel-body\">\r\n");
      out.write("        Nihil anim keffiyeh helvetica, craft beer labore wes anderson \r\n");
      out.write("        cred nesciunt sapiente ea proident. Ad vegan excepteur butcher \r\n");
      out.write("        vice lomo.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-heading\">\r\n");
      out.write("      <h4 class=\"panel-title\">\r\n");
      out.write("        <a data-toggle=\"collapse\" data-parent=\"#accordion\" \r\n");
      out.write("          href=\"#collapseThree\">\r\n");
      out.write("          点击我进行展开，再次点击我进行折叠。第 3 部分\r\n");
      out.write("        </a>\r\n");
      out.write("      </h4>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseThree\" class=\"panel-collapse collapse\">\r\n");
      out.write("      <div class=\"panel-body\">\r\n");
      out.write("        Nihil anim keffiyeh helvetica, craft beer labore wes anderson \r\n");
      out.write("        cred nesciunt sapiente ea proident. Ad vegan excepteur butcher \r\n");
      out.write("        vice lomo.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar-fixed-bottom\">\r\n");
      out.write("        <div class=\"footer white14\">&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;版权所有： 西安市交警支队车管所 &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("        &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;技术支持：陕西启翔景程电子科技股份有限公司</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"./content/footer_bottom.js.下载\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
